### ISSUE TITLE
Crashes on Razer Controller X

### ISSUE THREAD

**Issue by brianwh92** [XeroxDev/Loupedeck-plugin-YTMDesktop#3]
Mulitple crashes with general use on the Razer Stream Controller X

Not app breaking, but the volume adjustment doesn't seem to work here either.

Will save multiple logs if you'd like them.

Thanks so much, this app is really helpful! Willing to help were I can.

Thanks,
Brian

**Comment by XeroxDev** [comment]
Hey! I guess you're using YTMDesktop Version 1.13.0? If so, this version isn't supported due to major flaws. We recommend using [Nightly Release (May 2022)](https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2). 

If not, please state:
Version of YTMDesktop,
Software Version of your device
Plugin Version.

**Comment by brianwh92** [comment]
Awesome! I was not using this latest version.
Already seems like it's working better.

thanks so much for your help! :)
